project:
  type: website

website:
  ## Metadata
  title: "GloDB"
  #description: ""
  site-url: https://www.glodb.org
  open-graph: true
  #image: 
  #image-alt: 
  navbar:
    left:
      - href: index.qmd
        text: Home
      - download.qmd
      - about.qmd
      - contact.qmd

    tools:
      - icon: bluesky
        href: https://camilledelavaux.bsky.social
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/c383d893/AMF-LSU-Database-and-Pipeline2
          - text: Report a Bug
            href:  https://github.com/c383d893/AMF-LSU-Database-and-Pipeline2/issues
format:
  html:
    theme:
      light: flatly
      dark: darkly
#    css: styles.css
    toc: false


