---
title: "About"
---

These databases and pipelines are the result of a long-term collaboration across taxonomists, bioinformaticians, and ecologists to establish robust and user-friendly databases and pipelines for environmental identification of arbuscular mycorrhizal fungi (AMF). AMF associate with 80% of plant species worldwide, impacting plant growth, survival, community structure, and ecosystem function. AMF are not one homogenous group; AMF taxa have variable impacts on their plant hosts and terrestrial ecosystem function. Still, their biodiversity is poorly understood. We hope these open databases and pipelines help increase our understanding of AMF diversity, ecology, and biogeography.

We are continuously updating the LSU database and pipeline. Currently, an ESIIL working group is supporting our continued work to (1) develop the first curated long-read AMF database, (2) build robust, open-access phylogenetic pipelines for AMF identification across major gene regions; and (3) apply these novel tools to reassess global distribution patterns of AMF. Find more information here: https://esiil.org/working-groups/amf-biogeography-diversity

Please contact us with any questions, bugs, or suggestions!

-   Camille Delavaux - c.delavaux\@nioo.knaw.nl
-   Robert Ramos - robert.ramos\@stonybrook.edu
